---
# vars file for install-docker
prereqs:
  - ca-certificates
  - apt-transport-https
  - curl
  - software-properties-common

dockerpackages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin