---
galaxy_info:
  author: Wendell
  description: Install and configure KVM virtualization on Ubuntu and RedHat systems
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL  # Enterprise Linux (RedHat/CentOS)
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - kvm
    - virtualization
    - system
    - libvirt

dependencies: []
