---
- name: Create CA certificates directory
  file:
    path: /etc/pki/ca-trust/source/anchors
    state: directory
    mode: '0755'

- name: Copy CA certificate
  copy:
    src: "{{ ca_cert_file }}"
    dest: "/etc/pki/ca-trust/source/anchors/{{ ca_cert_file | basename }}"
    mode: '0644'
  notify: update ca certificates

- name: Force update CA certificates
  command: update-ca-trust extract
  changed_when: true
